package main.java.tests;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.nlogo.api.Argument;
import org.nlogo.api.Context;
import org.nlogo.api.ExtensionException;
import org.nlogo.api.Reporter;
import org.nlogo.core.Syntax;
import org.nlogo.core.SyntaxJ;

import burlap.behavior.valuefunction.QValue;
import burlap.mdp.core.state.State;
import burlap.statehashing.HashableState;
import main.java.burlap.QLearningAlgorithm;
import main.java.model.AgentLearning;
import main.java.model.Session;

public class VerifyLearningCommand implements Reporter{

	private static final String COMMA_DELIMITER = ";";

	@Override
	public Syntax getSyntax() {
		int [] src = {Syntax.StringType()};
		return SyntaxJ.reporterSyntax(src, Syntax.StringType());
	}

	@Override
	public Object report(Argument[] args, Context context) throws ExtensionException {
		// valores assistentes
		String src 						= args[0].getString();
		StringBuilder sb 				= new StringBuilder();
		QLearningAlgorithm learning 	= QLearningAlgorithm.getInstance(args, context);
		// verificar o algoritmo do agente, a fazer
		//AgentLearning agent = Session.getInstance().getAgent(context.getAgent());
		// tabelas q
		Map<State, List<QValue>> qtable = learning.getState();
		Map<List<Integer>, String> map 	= readFile(src);
		sb.append("QLEARNING VERIFIER\n");
		sb.append("File location: " + src + "\n\n");
		if(map.size() != qtable.size()) {
			throw new ExtensionException("The Q-Tables are not matching in size!\nSize of Q-Table: " + qtable.size() +"\nSize of CSV Q-Table: " + map.size() + "\nUse the command get-learning-details to see the full list of available states");
		}
		sb.append(verifyStates(qtable, map));
		
		return sb.toString();
	}
	
	private StringBuilder verifyStates(Map<State, List<QValue>> qtable, Map<List<Integer>, String> map) throws ExtensionException {
		Set<State> estado 			= qtable.keySet();
		Set<List<Integer>> chaves 	= map.keySet();
		boolean isEqual 			= true;
		StringBuilder sb 			= new StringBuilder();
		
		Iterator<State> itr 				= estado.iterator();
		Iterator<List<Integer>> itr_chave 	= chaves.iterator();
		
		while(itr.hasNext()) {
			State elemento 		= itr.next();
			boolean wasFound 	= false;
			
			while(itr_chave.hasNext()) {
				List<Integer> elemento_chave 	= itr_chave.next();
				double cord_x 					= (double) elemento.get("XCOR");
				double cord_y 					= (double) elemento.get("YCOR");;
				
				if(Double.compare(cord_x, elemento_chave.get(0)) == 0 && Double.compare(cord_y, elemento_chave.get(1)) == 0) {
					
					wasFound = true;
					List<QValue> maxQValue 	= findMaxQValue(qtable.get(elemento));
					String[] maxValues		= map.get(elemento_chave).split("-");
					
					for (int i = 0; i < maxValues.length; i++) {
						
						if(!maxQValue.get(i).a.actionName().contains(maxValues[i]) && !maxValues[i].contains("any")) {
							
							isEqual = false;
							sb.append("Different Action Found!\n");
							sb.append("State: "+ elemento_chave +"\nAction expected by the CSV table:" + maxValues[i] + "\nAction found on the Q-Table: " + maxQValue.get(i).a.actionName() + "\n\n");
						}
						
//						else {
//							
//							sb.append("State: "+ elemento_chave +"\nAction informed by the file:" + maxValues[i] + "\nAction generated by the extension: " + maxQValue.get(i).a.actionName() + "\n");
//
//						}

					}
				}
				if(!itr_chave.hasNext() && !wasFound) {
					throw new ExtensionException("State "+ cord_x + " " + cord_y + " was not found on the CSV table\nUse the command get-learning-details to see the full list of available states");
				}
			}
			itr_chave = chaves.iterator();
		}
		sb.append("\nActions verified, the result is...\n");
		if(isEqual) {
			sb.append("Both tables are equal!");
		}
		else {
			sb.append("Different values were found on the Q-Table!");
		}
		return sb;
	}
	
	private List<QValue> findMaxQValue(List<QValue> state) {
	    if (state == null || state.isEmpty()) {
	        return null; 
	    }
	    
	    if (state.size() == 1) {
	        return state;
	    }
	    List<QValue> values = new ArrayList<QValue>();
	    QValue firstMax = null;
	    QValue secondMax = null;

	    for (QValue qvalue : state) {
	        if (firstMax == null || qvalue.q > firstMax.q) {
	            secondMax = firstMax;
	            firstMax = qvalue; 
	        } 
	        else if (secondMax == null || qvalue.q > secondMax.q) {
	            secondMax = qvalue;
	        }
	    }
	    values.add(firstMax);
	    values.add(secondMax);
	    return values;
	}
	
	private Map<List<Integer>, String> readFile(String src){
		Map<List<Integer>, String> map 	= new HashMap<>();
		try (BufferedReader br 			= new BufferedReader(new FileReader(src))) {
		    String line 				= br.readLine();
		    while ((line = br.readLine()) != null) {
		    	String[] values 		= line.split(COMMA_DELIMITER);
		    	map.put(getStates(values[0]), values[1]);
		    }
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return map;
	}
	
	private List<Integer> getStates (String coord){
		List<Integer> states = new ArrayList<Integer>();
		for (String state: coord.split("-")) {
			states.add(Integer.parseInt(state));
		}
		return states;
	}
	
//	private List<String> getActions (String act){
//		List<String> actions = new ArrayList<String>();
//		for (String action: act.split("-")) {
//			actions.add(action);
//		}
//		return actions;
//	}

}
